version: '3'

services:
  app:
    image: codershisho/php
    container_name: app-my-goal
    tty: true
    volumes:
      - .:/var/www/
    ports:
      - 5173:5173

  nginx:
    image: codershisho/nginx
    container_name: nginx-my-goal
    tty: true
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mariadb:10.9
    container_name: mariadb-my-goal
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  db_data:
